### ISSUE TITLE
Do we still maintain this repo?

### ISSUE THREAD

**Issue by Colstuwjx** [TencentCloud/kubernetes-csi-tencentcloud#11]
It seems that our deployment yaml and driver code is behind the kubernetes CSI feature releases. Do we still maintain this repo?

**Comment by Colstuwjx** [comment]
@dbdd4us  I've been forked this repo, and did some changes according the requirements, and I'll be happy to pr those changes back to this upstream repo.

See [Colstuwjx/kubernetes-csi-tencentcloud #1](https://github.com/Colstuwjx/kubernetes-csi-tencentcloud/pull/1), and it also fixed #14 , and some tweaks including:

- [x] switch to go mod;
- [x] update deploy yamls;
- [x] make CSI dependencies up-to-date;
- [x] split snapshotter to snapshot controller and sidecar container;
- [x] enable leader election;
- [x] merged attacher and provisioner to controller

Thanks.

**Comment by malc0lm** [comment]
@Colstuwjx Thanks for your work, i think you can split your tweaks to single topic(tweak), and I will review it.  Welcome to contribution :)
