### ISSUE TITLE
从老版本插件升级到新版本以后, 报错如下:

### ISSUE THREAD

**Issue by ruanshudong** [TencentCloud/kubernetes-csi-tencentcloud#115]
running "VolumeBinding" filter plugin for pod "mysql-0": pod has unbound immediate PersistentVolumeClaims

persistentvolume-controller  waiting for a volume to be created, either by external provisioner "com.tencent.cloud.csi.cbs" or manually created by system administrator

这个是啥原因?

**Comment by huchengze** [comment]
controller 未正常创建出云盘，可以查一下 kube-system 命名空间下 deployment `csi-cbs-controller` 中 `csi-provisioner` 和 `cbs-csi` 容器的日志。
