### ISSUE TITLE
新版csi，node一定要有providerID ？

### ISSUE THREAD

**Issue by zong400** [TencentCloud/kubernetes-csi-tencentcloud#124]
I0816 07:52:03.015746   26751 main.go:44] Building kube configs for running in cluster...
I0816 07:52:03.016845   26751 driver.go:48] Driver: com.tencent.cloud.csi.cbs version: v2.2.7
I0816 07:52:05.036341   26751 metadata.go:37] region: ap-beijing
I0816 07:52:07.060484   26751 metadata.go:37] zone: ap-beijing-7
I0816 07:52:07.061471   26751 driver.go:102] Specify component type: node
E0816 07:52:09.075897   26751 node.go:552] the providerID in node k8s-dev-node9 is empty
E0816 07:52:11.068816   26751 node.go:552] the providerID in node k8s-dev-node9 is empty
E0816 07:52:13.068132   26751 node.go:552] the providerID in node k8s-dev-node9 is empty
E0816 07:52:15.068676   26751 node.go:552] the providerID in node k8s-dev-node9 is empty
E0816 07:52:17.069060   26751 node.go:552] the providerID in node k8s-dev-node9 is empty
E0816 07:52:19.068493   26751 node.go:552] the providerID in node k8s-dev-node9 is empty
E0816 07:52:21.069283   26751 node.go:552] the providerID in node k8s-dev-node9 is empty
E0816 07:52:23.068249   26751 node.go:552] the providerID in node k8s-dev-node9 is empty
E0816 07:52:25.068236   26751 node.go:552] the providerID in node k8s-dev-node9 is empty
E0816 07:52:27.064921   26751 node.go:548] get node k8s-dev-node9 failed, err: context deadline exceeded
F0816 07:52:27.064943   26751 node.go:557] get providerID from node k8s-dev-node9 failed before deadline exceeded

**Comment by system51** [comment]
你是否解决了？ 我也遇到了相同的问题。

**Comment by kinderyj** [comment]
CVM Node资源的providerID的格式如下：
tencentcloud://inx-xxx

参考：https://github.com/kubernetes/kubernetes/blob/2fef630dd216ddefd051ef5a2dda3fe1fdf7439a/pkg/apis/core/types.go#L3971

**Comment by zong400** [comment]
@kinderyj 是自己在node里面加？这个做法比较low啊
我从旧版csi升级的 ，describe里面其实有ins-id，不知道为什么新版要providerID里面拿

Annotations:        csi.volume.kubernetes.io/nodeid: {"com.tencent.cloud.csi.cbs":"ins-xxxxx"}
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true

**Comment by marshz9** [comment]
@kinderyj 
你好，我这里设置了 `ProviderID:                   tencentcloud://ins-xxxxxxxx`，但报错`E0818 09:40:20.615553  118007 node.go:527] invalid format for tencentcloud instance (tencentcloud://ins-xxxxxxxx)`。
看这里代码https://github.com/TencentCloud/kubernetes-csi-tencentcloud/blob/master/driver/cbs/node.go#L525 的意思，这里是只支持`kn`前缀的资源吗？

**Comment by zong400** [comment]
@marshz9 看代码应该是 qcloud://ins-xxxxx

**Comment by kinderyj** [comment]
> @kinderyj 你好，我这里设置了 `ProviderID: tencentcloud://ins-xxxxxxxx`，但报错`E0818 09:40:20.615553 118007 node.go:527] invalid format for tencentcloud instance (tencentcloud://ins-xxxxxxxx)`。 看这里代码https://github.com/TencentCloud/kubernetes-csi-tencentcloud/blob/master/driver/cbs/node.go#L525 的意思，这里是只支持`kn`前缀的资源吗？

已更新使用说明：
providerID: qcloud:///ins-xxxxx （当前版本已经支持）
providerID: tencentcloud://ins-xxx （待兼容）

**Comment by kinderyj** [comment]
> 



> @kinderyj 是自己在node里面加？这个做法比较low啊 我从旧版csi升级的 ，describe里面其实有ins-id，不知道为什么新版要providerID里面拿
> 
> Annotations: csi.volume.kubernetes.io/nodeid: {"com.tencent.cloud.csi.cbs":"ins-xxxxx"} node.alpha.kubernetes.io/ttl: 0 volumes.kubernetes.io/controller-managed-attach-detach: true

这个providerId不用自己设置的。你们现在集群是自建的K8s？ kubectl get node -oyaml |grep providerID
输出内容辛苦贴一下

**Comment by system51** [comment]
@marshz9 tencentcloud://ins-xxxxxxxx 这种方式暂不知，需要等更新。 如果你现在已经设置了这个值就有点惨了，我试了一下我在我的集群 ProviderID 这个值不支持删除不支持更新

**Comment by zong400** [comment]
@kinderyj 是自建的k8s，刚刚升级1.19.16，get node和describe node都没有这个providerID

**Comment by kinderyj** [comment]
> 

近期会出新版本兼容这个场景

**Comment by kinderyj** [comment]
> 



> @kinderyj 是自建的k8s，刚刚升级1.19.16，get node和describe node都没有这个providerID

近期会出新版本兼容自建场景。

**Comment by zong400** [comment]
> > 
> 
> > @kinderyj 是自建的k8s，刚刚升级1.19.16，get node和describe node都没有这个providerID
> 
> 近期会出新版本兼容自建场景。

好的，期待

**Comment by huchengze** [comment]
@zong400 @system51 @marshz9 
使用 master 分支最新的配置文件即可兼容自建的场景。
或者手动删除 daemonset `csi-cbs-node` 中 `cbs-csi` 容器的环境变量 `NODE_ID`。

**Comment by zong400** [comment]
@huchengze 谢谢，我升级测试环境看看
