### ISSUE TITLE
文件存储：资源不足: 文件系统数量达到上限

### ISSUE THREAD

**Issue by guolong123** [TencentCloud/kubernetes-csi-tencentcloud#128]
创建pvc30个就报这个错误了，这个限制在k8s这种使用场景下根本没法用啊？
![image](https://user-images.githubusercontent.com/22833963/201286675-8a1fe1a6-3dad-4cd2-ab79-cc00c96021e3.png)

**Comment by huchengze** [comment]
这里的限制是指单个用户最多创建这么多个 cfs 文件系统，由于每个文件系统实际存储空间都很大，所以不需要创建这么多。
cfs-csi 插件支持 rwx 的挂载模式，即不同节点的 pod 可以指定同一个 pvc 来访问同一个文件系统；也可以通过静态存储的方式复用同一个文件系统给多个 pv，pvc。

**Comment by guolong123** [comment]
> 这里的限制是指单个用户最多创建这么多个 cfs 文件系统，由于每个文件系统实际存储空间都很大，所以不需要创建这么多。 cfs-csi 插件支持 rwx 的挂载模式，即不同节点的 pod 可以指定同一个 pvc 来访问同一个文件系统；也可以通过静态存储的方式复用同一个文件系统给多个 pv，pvc。

主要问题是需要使用sc来动态申请存储，官方给的例子默认就是申请一个文件系统啊，而且貌似没有直接申请已存在文件系统的子路径。不同pod指定同一个pvc，挂载的路径实际上是一样的，那要在业务上做路径区别，这个肯定不行。另一个静态存储的方式，对现有的申请存储的方式改动有点大。插件是否可以直接支持在已有的文件系统中动态创建pv？

**Comment by huchengze** [comment]
在 TKE 上给 cfs 组件新增了一个 tcfs 微服务，可以通过这个服务来做单个文件系统的动态存储，动态生成的不同 pv 分别指向文件系统中的不同子目录，但这个微服务暂时还没有开源的计划。
https://cloud.tencent.com/document/product/457/44235#.E5.88.9B.E5.BB.BA-storageclass
