### ISSUE TITLE
关于使用子账号授权cbs权限创建无权限问题

### ISSUE THREAD

**Issue by duiniwukenaihe** [TencentCloud/kubernetes-csi-tencentcloud#24]
![12345](https://user-images.githubusercontent.com/15711623/88247532-a7480400-ccd0-11ea-8378-f85cc502a044.png)
![123456](https://user-images.githubusercontent.com/15711623/88247537-a9aa5e00-ccd0-11ea-91c3-211d4a03ff86.png)
鉴于权限问题开通了子账号，权限都已经添加但是没有权限创建pvc,一直pending，更换账号与秘钥为母账户可正常操作，请问子账号权限是否有限制呢？

**Comment by ruanshudong** [comment]
你用的k8是啥版本, 我用1.18.6, 部署都不成功啊

**Comment by duiniwukenaihe** [comment]
我的也是1.18.6可以的都是操作系统centos7。centos8貌似不成功

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ivan-cai** [comment]
> ![12345](https://user-images.githubusercontent.com/15711623/88247532-a7480400-ccd0-11ea-8378-f85cc502a044.png)
> ![123456](https://user-images.githubusercontent.com/15711623/88247537-a9aa5e00-ccd0-11ea-91c3-211d4a03ff86.png)
> 鉴于权限问题开通了子账号，权限都已经添加但是没有权限创建pvc,一直pending，更换账号与秘钥为母账户可正常操作，请问子账号权限是否有限制呢？

这个报错是uin没有支付权限，需要检查一下授权情况

**Comment by duiniwukenaihe** [comment]
已经解决，建议更新下部署文档里面的 api version。要求的具体权限 详细说明下，另外kubernets1.19版本文档是跑不起来的，需要更新csi-node.yaml中csi-node-driver-registrar镜像版本我是直接更新到了官方的v2.0.1然后还需要给work节点增加lable 
 topology.com.tencent.cloud.csi.cbs/zone=

**Comment by ivan-cai** [comment]
@duiniwukenaihe 好的 感谢 目前腾讯云还没有支持>1.18版本的集群 所以暂时没有遇到这些问题 后续上新版本，我们做了测试后更新上
