### ISSUE TITLE
删除pod以后, pv一直处于removing可能什么原因?

### ISSUE THREAD

**Issue by ruanshudong** [TencentCloud/kubernetes-csi-tencentcloud#27]
[root@VM-0-4-centos TencentCBS]# kubectl describe pv pvc-d98fe410-ebfd-4c06-b600-ffe286bbd6f8
Name:              pvc-d98fe410-ebfd-4c06-b600-ffe286bbd6f8
Labels:            <none>
Annotations:       pv.kubernetes.io/provisioned-by: com.tencent.cloud.csi.cbs
Finalizers:        [external-attacher/com-tencent-cloud-csi-cbs]
StorageClass:      cbs-premium
Status:            Terminating (lasts 3m37s)
Claim:             default/csi-pvc-2
Reclaim Policy:    Delete
Access Modes:      RWO
VolumeMode:        Filesystem
Capacity:          10Gi
Node Affinity:     
  Required Terms:  
    Term 0:        topology.com.tencent.cloud.csi.cbs/zone in [ap-guangzhou-3]
Message:           
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            com.tencent.cloud.csi.cbs
    FSType:            ext4
    VolumeHandle:      disk-s1b9pe7a
    ReadOnly:          false
    VolumeAttributes:      diskType=CLOUD_PREMIUM
                           storage.kubernetes.io/csiProvisionerIdentity=1598996233021-8081-com.tencent.cloud.csi.cbs
Events:
  Type     Reason              Age    From                                                                    Message
  ----     ------              ----   ----                                                                    -------
  Warning  VolumeFailedDelete  3m44s  com.tencent.cloud.csi.cbs_master1_606d5d83-b8de-425f-8838-8c941d3abf9e  rpc error: code = Internal desc = [TencentCloudSDKError] Code=InvalidParameter, Message=(afdbb3a45ed8)disk(disk-s1b9pe7a) is attached, please detach first, RequestId=5e2a9c0f-014b-4c2b-8858-afdbb3a45ed8
  Warning  VolumeFailedDelete  3m44s  com.tencent.cloud.csi.cbs_master1_dda92a0d-ac65-4d1b-9a3d-5afe6745caaa  rpc error: code = Internal desc = [TencentCloudSDKError] Code=InvalidParameter, Message=(431d7476c076)disk(disk-s1b9pe7a) is attached, please detach first, RequestId=10b7fcbd-b181-4ad1-8835-431d7476c076
  Warning  VolumeFailedDelete  3m43s  com.tencent.cloud.csi.cbs_master1_606d5d83-b8de-425f-8838-8c941d3abf9e  rpc error: code = Internal desc = [TencentCloudSDKError] Code=InvalidParameter, Message=(3a71671373e9)disk(disk-s1b9pe7a) is attached, please detach first, RequestId=fedbd4bd-9889-4f11-9ac0-3a71671373e9
  Warning  VolumeFailedDelete  3m43s  com.tencent.cloud.csi.cbs_master1_dda92a0d-ac65-4d1b-9a3d-5afe6745caaa  rpc error: code = Internal desc = [TencentCloudSDKError] Code=InvalidParameter, Message=(605d26c1b910)disk(disk-s1b9pe7a) is attached, please detach first, RequestId=9559c338-151c-4a61-b428-605d26c1b910
  Warning  VolumeFailedDelete  3m41s  com.tencent.cloud.csi.cbs_master1_606d5d83-b8de-425f-8838-8c941d3abf9e  rpc error: code = Internal desc = [TencentCloudSDKError] Code=InvalidParameter, Message=(4d464ba3e1aa)disk(disk-s1b9pe7a) is detaching, please retry later, RequestId=bf09f91a-04c9-4476-860d-4d464ba3e1aa
  Warning  VolumeFailedDelete  3m41s  com.tencent.cloud.csi.cbs_master1_dda92a0d-ac65-4d1b-9a3d-5afe6745caaa  rpc error: code = Internal desc = [TencentCloudSDKError] Code=InvalidParameter, Message=(762fae7f4615)disk(disk-s1b9pe7a) is detaching, please retry later, RequestId=82df0dcd-15b1-453b-9160-762fae7f4615
  Warning  VolumeFailedDelete  3m37s  com.tencent.cloud.csi.cbs_master1_606d5d83-b8de-425f-8838-8c941d3abf9e  rpc error: code = Internal desc = [TencentCloudSDKError] Code=InvalidParameter, Message=(21dcb10b2a7c)disk(disk-s1b9pe7a) is detaching, please retry later, RequestId=47be871c-5194-4206-9d9e-21dcb10b2a7c

**Comment by ivan-cai** [comment]
@ruanshudong 这个问题依然存在吗？我看磁盘已经被删除了

**Comment by ruanshudong** [comment]
磁盘删除是没问题的, 但是k8s上残留了pvc的记录, 一直在Removing中

**Comment by ivan-cai** [comment]
我的微信号是ivans_cj

**Comment by ruanshudong** [comment]
我不是用的tke, 自己在腾讯云上部署的k8s

**Comment by ruanshudong** [comment]
晚点加你微信

**Comment by ivan-cai** [comment]
那可以查看下controller manager的日志 如果一直报错你贴出来的错误 就得找腾讯云的云硬盘同事定位下了
