### ISSUE TITLE
在SECRET_ID/KEY权限正常的情况下，csi创建云盘报错请求签名认证失败

### ISSUE THREAD

**Issue by anningzxd** [TencentCloud/kubernetes-csi-tencentcloud#47]
![image](https://user-images.githubusercontent.com/20147824/110609564-4ff79500-81c8-11eb-903b-5ad1d118c27c.png)
我的集群环境为1.18.3。ECRET_ID/KEY均做了base64转换，并且在腾讯云在线调用可以创建磁盘。
但是我在集群内使用csi创建cbs时，仍然报错：生成的签名是错误的。
请问这是什么情况呢？

**Comment by ivan-cai** [comment]
应该是csi-controller.yaml和csi-node.yaml中对应的环境变量名有变化。TENCENTCLOUD_API_SECRET_ID、TENCENTCLOUD_API_SECRET_KEY
对比下你正在运行的yaml和https://github.com/TencentCloud/kubernetes-csi-tencentcloud/blob/master/deploy/cbs/kubernetes/csi-controller.yaml#L123
