### ISSUE TITLE
生产上运行CBS的CSI，突然今天：请求签名验证失败，请检查您的签名计算是否正确

### ISSUE THREAD

**Issue by Warren-Xia** [TencentCloud/kubernetes-csi-tencentcloud#49]
【问题描述】我们是在云主机上安装的openshift
使用https://github.com/TencentCloud/kubernetes-csi-tencentcloud/blob/master/deploy/cbs/kubernetes/csi-node.yaml 时候报错：I0330 09:01:48.553058 1 connection.go:183] GRPC request: {"accessibility_requirements":{"preferred":[{"segments":{"topology.com.tencent.cloud.csi.cbs/zone":"ap-shanghai-4"}}],"requisite":[{"segments":{"topology.com.tencent.cloud.csi.cbs/zone":"ap-shanghai-4"}}]},"capacity_range":{"required_bytes":10737418240},"name":"pvc-ac78e6eb-9134-11eb-9a9a-52540095d716","parameters":{"aspId":"asp-601v5u5s","diskType":"CLOUD_PREMIUM","diskZones":"ap-shanghai"},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}}]}
 
I0330 09:01:48.678439 1 connection.go:185] GRPC response: {}
 
I0330 09:01:48.679013 1 connection.go:186] GRPC error: rpc error: code = InvalidArgument desc = [TencentCloudSDKError] Code=AuthFailure.SignatureFailure, Message=请求签名验证失败，请检查您的签名计算是否正确。, RequestId=fe2bb395-4aab-401c-b53c-77475d9a0547

江湖救急，帮帮忙

**Comment by ivan-cai** [comment]
应该是csi-controller.yaml和csi-node.yaml中对应的环境变量名有变化。TENCENTCLOUD_API_SECRET_ID、TENCENTCLOUD_API_SECRET_KEY
对比下你正在运行的yaml和https://github.com/TencentCloud/kubernetes-csi-tencentcloud/blob/master/deploy/cbs/kubernetes/csi-controller.yaml#L123

**Comment by a95241815** [comment]
我的是开始就遇到这个问题，是参考https://blog.csdn.net/saynaihe/article/details/115212770这个文章操作的。帮忙看看
![888](https://user-images.githubusercontent.com/15665797/128224287-18ae08bc-0cbb-4e68-b027-79e5a7a0b22d.png)

**Comment by kinderyj** [comment]
> 我的是开始就遇到这个问题，是参考[https://blog.csdn.net/saynaihe/article/details/115212770这个文章操作的。帮忙看看](https://blog.csdn.net/saynaihe/article/details/115212770%E8%BF%99%E4%B8%AA%E6%96%87%E7%AB%A0%E6%93%8D%E4%BD%9C%E7%9A%84%E3%80%82%E5%B8%AE%E5%BF%99%E7%9C%8B%E7%9C%8B)
> ![888](https://user-images.githubusercontent.com/15665797/128224287-18ae08bc-0cbb-4e68-b027-79e5a7a0b22d.png)

**Comment by kinderyj** [comment]
https://github.com/TencentCloud/kubernetes-csi-tencentcloud/blob/master/deploy/cbs/kubernetes/secret.yaml
需要检查一下这里的secretId和key是否正确填写，以及是否做了base64
