### ISSUE TITLE
kubernetes 1.12以下版本对接tencentcloud cbs有什么推荐方案吗？

### ISSUE THREAD

**Issue by jeremyxu2010** [TencentCloud/kubernetes-csi-tencentcloud#6]
RT。由于历史原因，当前部署的是kubernetes 1.11.6版本，而且上面已经部署了较多应用，不太好对kubernetes进行升级。这个版本没法使用CSI插件，这种情况下又想对接tencentcloud cbs，请问有什么推荐方案吗？

**Comment by malc0lm** [comment]
1.12以下版本请使用 release-0.2.1分支的csi版本
